# Project information
site_name: VGG Docs

# Repository
edit_uri: https://github.com/verygoodgraphics/vgg_docs/blob/main/docs/

# Copyright
copyright: Copyright &copy; 2023 VeryGoodGraphics LTD.

# Page tree
nav:
  - 'Home':
    - 'index.md'
    - 'What is...':
      - 'VGG Daruma': 'what/daruma.md'
      - 'VGG Runtime': 'what/runtime.md'
      - 'Their Relationship': 'what/relation.md'
      - 'Developer Tools': 'what/tools.md'
    - 'Quick Start': 'quick_start.md'
    - 'FAQ': 'faq.md'
  - 'Examples':
    - 'Overview': 'examples/index.md'
  - 'Components':
    - 'Overview': 'components/index.md'
    - 'React': 'components/react.md'
  - 'Widgets':
    - 'Overview': 'widgets/index.md'
  - 'SDKs':
    - 'Overview': 'sdks/index.md'
    - 'JavaScript SDK': 'sdks/js_sdk.md'
  - 'Plugins':
    - 'Overview': 'plugins/index.md'

# Configuration
theme:
  name: material
  palette:
    primary: white
  logo: assets/images/favicon.svg
  favicon: assets/images/favicon.svg
  icon:
    edit: material/pencil
  features:
    # - announce.dismiss
    - content.action.edit
    # - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    # - navigation.sections     # don't enable
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate

# Customization
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/VGG_Design
    - icon: fontawesome/brands/github
      link: https://github.com/verygoodgraphics
    - icon: fontawesome/brands/discord
      link: https://discord.gg/vB3bcSvNvb
    # - icon: fontawesome/solid/envelope
    #   link: mailto:<bd@verygoodgraphics.com>

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
