# Project information
site_name: VGG Docs

# Repository
repo_url: https://github.com/verygoodgraphics/vgg_docs
edit_uri: blob/main/docs/

# Page tree
nav:
  - 'Get Started': 'index.md'
  - 'Quick Start': 'quick_start.md'
  - 'Tutorial':
    - 'Import a layout': 'tutorial/import_layout.md'
    - 'Bind elements': 'tutorial/bind_elements.md'
    - 'Write codes': 'tutorial/write_codes.md'
    - 'Generate the APP': 'tutorial/generate_app.md'
  - 'Products':
    - Editor: 'products/editor.md'
    - 'Dev Tools': 'products/dev_tools.md'
  - 'Examples':
    - 'Widget gallery': 'examples/widget_gallery.md'
  - 'API': 'api.md'
  - 'FAQ': 'faq.md'

# Configuration
theme:
  name: material
  palette:
    primary: white
  logo: assets/images/favicon.svg
  features:
    # - announce.dismiss
    - content.action.edit
    # - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate

# Customization
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/VGG_Design
    - icon: fontawesome/brands/github
      link: https://github.com/verygoodgraphics
    - icon: fontawesome/brands/discord
      link: https://discord.gg/g3HJuKP54D
    - icon: fontawesome/solid/envelope
      link: mailto:<bd@verygoodgraphics.com>

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
