/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  specSidebar: [
    {
      type: "doc",
      id: "specs/overview",
      label: "Overview",
    },
    "specs/file",
    {
      type: "category",
      label: "Vector Graphics Spec",
      link: {
        type: "doc",
        id: "specs/vectorgraphics/overview",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "specs/vectorgraphics",
        },
      ],
    },
    {
      type: "category",
      label: "Layout Spec",
      link: {
        type: "doc",
        id: "specs/layout/overview",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "specs/layout",
        },
      ],
    },
    "specs/animation",
    "specs/3d",
    "specs/script",
  ],

  featSidebar: [
    {
      type: "doc",
      id: "features/overview",
      label: "Overview",
    },
    {
      type: "category",
      label: "Graphic Features",
      items: [
        {
          type: "category",
          label: "Blurs",
          items: [
            {
              type: "autogenerated",
              dirName: "features/graphic/Blurs",
            },
          ]
        },
        {
          type: "category",
          label: "Borders",
          link: {
            type: "doc",
            id: "features/graphic/borders",
          },
          items: [
            {
              type: "autogenerated",
              dirName: "features/graphic/Borders",
            },
          ]
        },
        {
          type: "category",
          label: "Fills",
          items: [
            {
              type: "autogenerated",
              dirName: "features/graphic/Fills",
            },
          ]
        },
        {
          type: "category",
          label: "Masks",
          items: [
            {
              type: "autogenerated",
              dirName: "features/graphic/Masks",
            },
          ]
        },
        {
          type: "category",
          label: "Shadows",
          items: [
            {
              type: "autogenerated",
              dirName: "features/graphic/Shadows",
            },
          ]
        },
        {
          type: "category",
          label: "Geometry",
          items: [
            {
              type: "autogenerated",
              dirName: "features/graphic/Geometry",
            },
          ]
        },
        {
          type: "doc",
          id: "features/graphic/image_filters",
        },
        {
          type: "doc",
          id: "features/graphic/blend_modes",
        },
        {
          type: "category",
          label: "Text",
          items: [
            {
              type: "autogenerated",
              dirName: "features/graphic/Text",
            },
          ]
        },
      ],
    },
  ],

  workflowSidebar: [
    {
      type: "autogenerated",
      dirName: "workflow",
    },
  ],

  containerSidebar: [
    {
      type: "autogenerated",
      dirName: "containers",
    },
  ],

  exampleSidebar: [
    "examples/overview",
    {
      type: "category",
      label: "JS/TS",
      items: [
        {
          type: "autogenerated",
          dirName: "examples/js",
        },
      ],
    },
    {
      type: "category",
      label: "React Demos",
      items: [
        {
          type: "autogenerated",
          dirName: "examples/react",
        },
      ],
    },
    {
      type: "category",
      label: "Vue Demos",
      items: [
        {
          type: "autogenerated",
          dirName: "examples/vue",
        },
      ],
    },
    {
      type: "category",
      label: "Svelte Demos",
      items: [
        {
          type: "autogenerated",
          dirName: "examples/svelte",
        },
      ],
    },
  ],
}

export default sidebars
