/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  specSidebar: [
    {
      Specs: [
        {
          type: "doc",
          id: "specs/overview",
          label: "Overview",
        },
        "specs/file",
        {
          type: "category",
          label: "Vector Graphics Spec",
          link: {
            type: "doc",
            id: "specs/vectorgraphics/overview",
          },
          items: [
            {
              type: "autogenerated",
              dirName: "specs/vectorgraphics",
            },
          ],
        },
        {
          type: "category",
          label: "Layout Spec",
          link: {
            type: "doc",
            id: "specs/layout/overview",
          },
          items: [
            {
              type: "autogenerated",
              dirName: "specs/layout",
            },
          ],
        },
        "specs/animation",
        "specs/3d",
        "specs/script",
        {
          type: "doc",
          id: "specs/changelog",
          label: "Changelog",
        },
      ],
    },
  ],

  featSidebar: [
    {
      Features: [
        {
          type: "doc",
          id: "features/overview",
          label: "Overview",
        },
        {
          type: "category",
          label: "Graphic Features",
          collapsed: false,
          items: [
            {
              type: "category",
              label: "Blurs",
              items: [
                {
                  type: "autogenerated",
                  dirName: "features/graphic/blurs",
                },
              ]
            },
            {
              type: "category",
              label: "Borders",
              items: [
                {
                  type: "autogenerated",
                  dirName: "features/graphic/borders",
                },
              ]
            },
            {
              type: "category",
              label: "Fills",
              items: [
                {
                  type: "autogenerated",
                  dirName: "features/graphic/fills",
                },
              ]
            },
            {
              type: "category",
              label: "Masks",
              items: [
                {
                  type: "autogenerated",
                  dirName: "features/graphic/masks",
                },
              ]
            },
            {
              type: "category",
              label: "Shadows",
              items: [
                {
                  type: "autogenerated",
                  dirName: "features/graphic/shadows",
                },
              ]
            },
            {
              type: "category",
              label: "Geometry",
              items: [
                {
                  type: "autogenerated",
                  dirName: "features/graphic/geometry",
                },
              ]
            },
            {
              type: "doc",
              id: "features/graphic/image_filters",
            },
            {
              type: "doc",
              id: "features/graphic/blend_modes",
            },
            {
              type: "category",
              label: "Text",
              items: [
                {
                  type: "autogenerated",
                  dirName: "features/graphic/text",
                },
              ]
            },
          ],
        },
        {
          type: "category",
          label: "Layout Features",
          collapsed: false,
          items: [
            {
              type: "category",
              label: "Constraints",
              items: [
                {
                  type: "autogenerated",
                  dirName: "features/layout/constraints",
                },
              ],
            },
            {
              type: "category",
              label: "Flexbox Layout",
              items: [
                {
                  type: "autogenerated",
                  dirName: "features/layout/flexbox",
                },
              ],
            },
          ],
        },
      ],
    },
  ],

  workflowSidebar: [
    {
      Workflow: [
        {
          type: "autogenerated",
          dirName: "workflow",
        },
      ],
    },
  ],

  containerSidebar: [
    {
      Containers: [
        {
          type: "autogenerated",
          dirName: "containers",
        },
      ],
    },
  ],

  exampleSidebar: [
    {
      Examples: [
        {
          type: "doc",
          id: "examples/overview",
          label: "Overview",
        },
        {
          type: "doc",
          id: "examples/basic-components/overview",
          label: "Basic Components",
        },
        {
          type: "doc",
          id: "examples/composite-components/overview",
          label: "Composite Components",
        },
        {
          type: "category",
          label: "Business Components",
          link: {
            type: "doc",
            id: "examples/business-components/overview",
          },
          items: [
            {
              type: "category",
              label: "JS/TS",
              items: [
                {
                  type: "autogenerated",
                  dirName: "examples/business-components/js",
                },
              ],
            },
            {
              type: "category",
              label: "React Demos",
              items: [
                {
                  type: "autogenerated",
                  dirName: "examples/business-components/react",
                },
              ],
            },
            {
              type: "category",
              label: "Vue Demos",
              items: [
                {
                  type: "autogenerated",
                  dirName: "examples/business-components/vue",
                },
              ],
            },
            {
              type: "category",
              label: "Svelte Demos",
              items: [
                {
                  type: "autogenerated",
                  dirName: "examples/business-components/svelte",
                },
              ],
            },
          ],
        },
      ],
    },
  ],
}

export default sidebars
